- collaboration/README.md
I updated the collaboration readme with group norms.
> Add group norms

- README.md
---
name: Main Readme - Milestone 0
about: For the first Milestone, we will add a brief overview for the project and an introduction to our team name and members
---
> Main readme - milestone 0

- collaboration/communication.md
- collaboration/retrospective.md
---
name: Retrospective Document PR
about: Template for Pull Requests submitting or updating retrospective documents.
---
> Add Milestone 0 Retrospective

- collaboration/learning_goals.md
---
Name: Learning goals 
about: Add the Learninggoals of the team.  
---
> Learning goals

- collaboration/communication.md
---
name: Update on the Communication
about: Add latest meeting's agenda, discussion topics and action points in the communications file
---
> update on the communication file

- collaboration/meeting_minutes/milestone_1_06_11_meeting_06.md
---
name: Meeting 6 Recap
about: the recap of meeting 6
---
> add meeting 6 min

- collaboration/meeting_minutes/milestone_0_05_29_meeting_01.md
- collaboration/meeting_minutes/milestone_0_06_03_meeting_02.md
- collaboration/meeting_minutes/milestone_1_06_08_meeting_04.md
- collaboration/meeting_minutes/milestone_1_06_10_meeting_05.md
---
name: Documentation & Formatting Fixes PR
about: address minor documentation errors, markdown formatting issues, or
display corrections.
---
This Pull Request addresses minor markdown formatting issues in the meeting minutes documents. Specifically, it resolves instances where dates, times, and links were incorrectly displayed on a single line due to the absence of two spaces at the
end of the preceding line, which are necessary for proper line breaks in Markdown.
The following files have been updated:
* `collaboration/meeting_minutes/milestone_0_05_29_meeting_01.md`
* `collaboration/meeting_minutes/milestone_0_06_03_meeting_02.md`
* `collaboration/meeting_minutes/milestone_1_06_08_meeting_04.md`
* `collaboration/meeting_minutes/milestone_1_06_10_meeting_05.md`
where needed.
Closes …
> Fix: Markdown Formatting in Meeting Minutes

- collaboration/meeting_minutes/milestone_1_06_13_meeting_08.md
---
Adding Meeting 08 meetings 
---
Added the minutes for Meeting #08 (Literature Reviews & Next Steps) held on June 13, 2025. The file includes:
- Meeting Points
- Action items agreed upon by the team
- Links to reference documents
- Attendee list and meeting details
> Add Meeting #08 minutes

- collaboration/meeting_minutes/milestone_1_06_12_meeting_07.md
---
Minutes Meeting #7
---
to prepare the minutes meeting #7 file
> preparing the minutes meeting #7

- collaboration/retrospectives/1_problem_identification.md
---
name: Retrospective Document PR
about: Updating the retrospective file for milestone 1
---
**Document Link**
* [Link to the Retrospective Document](collaboration/retrospectives/1_problem_identification.md)
---
---
Closes [#58 ](https://github.com/MIT-Emerging-Talent/ET6-CDSP-group-24-repo/issues/58)
> Add Milestone 1 Retrospective

- README.md
---
Problem Statement
---
Added the problem statement of our research question in the repository README
> Adding problem statement

- 0_domain_study/background_review.md
---
name: Domain background review
about: A thorough background research review for the problem domain
---
> Background review

- collaboration/README.md
- collaboration/communication.md
- collaboration/constraints.md
- collaboration/learning_goals.md
---
Milestone 1: Maintain planning documents
This PR updates planning documents for Milestone 1, including group norms , learning goals, constraints, and the communication plan. Review logs were also added to each file.  
---
> Add review logs to planning documents

- README.md
---
Repository Readme Enhancements
---
I made a few enhancements in the repository readme, please check the issue #75 for full details
> Few enhancements to Repository Readme

- 0_domain_study/README.md
---
Domain Study Readme
---
Added the structure and overview of our domain study in README
> Adding domain_study readme content

- README.md
---
Contributing file fix
---
Fixed the contributing file link in the repository readme
> fixed contributing.md link

- 0_domain_study/research_notes/initial_research_questions.md
---
Initial research questions
---
Closes [#61 ](https://github.com/MIT-Emerging-Talent/ET6-CDSP-group-24-repo/issues/61)
> M1: Add initial research questions

- 0_domain_study/README.md
---
Domain Study Readme Fixes
---
Fixed some issues with the file links in the domain study readme
> fixed files links issues

- collaboration/meeting_minutes/milestone_2_06_19_meeting_11.md
This PR adds the meeting minutes for **Meeting#11**, held on **Thursday, June 19, 2025**.
This meeting marked the **true kick-off of Milestone 2** and involved a key **strategic decision**: to pivot toward a *data-first* approach. Rather than narrowing the research question first, the team agreed to explore available data to ensure our research direction is grounded, feasible, and impactful.
> _"With data as our compass and collective insight as our guide, we've set a powerful new course."_
---
Closes: #85
Relates to: #84, #86
---
- `collaboration/meeting_minutes/milestone_2_06_19_meeting_11.md` 
---
- Please review the meeting summary and structure.
- Let me know if anything from the discussion is missing or needs clarification.
---
> Add Meeting Minutes #11 - Strategic Pivot & Milestone 2 Launch

- collaboration/meeting_minutes/milestone_2_06_23_meeting_13.md
---
Meeting Minutes #13 
---
To prepare the 13th Meeting minutes that describes about discussing how to synchronize the collected datasets and Plan the deliverables.
> Preparation of 13th Meeting Minutes

- 1_datasets/tech_ecosystem.md
---
Tech EcoSystem & Feedback Channels Theme Datasets
---
Added the documentation for all the datasets collected for the theme
Closes #97
> Tech EcoSystem & Feedback Channels Theme Datasets

- README.md
---
name: General PR template
about: A template with a generic and high-level review checklist, feel free to modify the checklists based on your PR.  
---
> Add GIF to our approach

- 1_datasets/digital_infrastructure.md
Digital Infrastructure Datasets Documentation
---
This PR adds structured documentation for 20 datasets analyzing digital infrastructure accessibility in Sub-Saharan Africa, with a focus on barriers faced by persons with disabilities (PWDs).
---
> Digital infrastructure datasets

- collaboration/retrospectives/2_data_collection_group_retrospective.md
- collaboration/retrospectives/2_data_collection_individual_reflections.md
---
This Pull Request finalizes and adds the retrospective documents for **Milestone 2: Data Collection**.
**Key changes in this PR include:**
* **Renaming** the main retrospective document for clarity:
`collaboration/retrospectives/2_data_collection.md` -> `collaboration/retrospectives/2_data_collection_group_retrospective.md`
* **Updating the content** of the Group Retrospective with final insights, lessons learned, and action plans.
* **Adding the new Individual Retrospective file:**
`collaboration/retrospectives/2_data_collection_individual_reflections.md`
* Integrating a link from the Group Retrospective to the Individual Reflections for easy navigation.
---
---
Closes #113
> Add M2 Data Collection Retrospectives

- README.md
---
Minor Fixes and enhancements to the main README file
---
- Enhance the alt texts to the images
- Fix the bullet points issue showing besides each other
- Fix large logo issue
Closes #115
> Main README Minor Fixes

- collaboration/meeting_minutes/milestone_3_07_07_meeting_16.md
---
**Meeting 16 - Manual Thematic Coding**
This PR adds the meeting minutes for our team meeting held on Monday, July 07, 2025, focused on reviewing the manual thematic coding process and planning its integration with the NLP workflow.
---
> Add Meeting Minutes 16 – Milestone 3 (07/07)

- collaboration/meeting_minutes/milestone_3_07_10_meeting_17.md
---
Meeting 17: Sub-Team Roles & Workflow Coordination
---
The meeting successfully clarified team roles and collaboration methods for the
upcoming hybrid analysis workflow. Participants were assigned to either the
Manual Coding or NLP team based on interest and availability.
closes: #123
> Add Meeting Minutes 17 – Milestone 3 (07/10)

- collaboration/meeting_minutes/milestone_3_07_14_meeting_18.md
This PR adds the meeting minutes for **Meeting#18**, held on **Monday, July 14, 2025**.
This session focused on crucial discussions around dataset quality, fit, and the formalization of our 4-tier triage model for manual vs. NLP analysis. We also clarified our shared understanding of data relevance, especially given current data constraints, and outlined the strategy for refining our analysis pipelines.
> "We’re not just cleaning data—we’re building the logic that gives our analysis integrity. With clarity and flexibility, we move forward to build something that matters."
---
Closes: #132
Relates to: #125, #127, #119
---
- `collaboration/meeting_minutes/milestone_3_07_14_meeting_18.md`
---
- Please review the meeting summary, key outcomes, and action points.
- Let me know if anything from …
> Add M3 Meeting Minutes #18 – Dataset Triage & Relevance Strategy

- 4_data_analysis/README.md
Added summaries of KWIC and BERTopic notebooks to the README 
closes #174
> Data Analysis Readme

- 4_data_analysis/manual_analysis_technical_description.md
**Closes #166**
This Pull Request delivers the "Technical Description (Manual Coding)" for Milestone 3, Deliverable 2.
It adds the `manual_analysis_technical_description.md` file to the `4_data_analysis/` directory. This document provides a comprehensive overview of our manual coding methodology, including:
* Our hybrid deductive-inductive coding approach.
* The process for sample selection.
* Details on intercoder calibration and reconciliation within our 3-member sub-team.
* The workflow for individual coding and cross-review.
* A justification for why manual coding was chosen for this subset of data.
* Acknowledged limitations and discussed alternative/complementary approaches.
This work complements the NLP-based analysis by grounding our project's findings in rich human narratives and …
> Add M3D2 Manual Coding Technical Description

- 4_data_analysis/README.md
---
Manual Coding Summary
---
This PR adds the manual analysis summary to the `data_analysis` README
> Manual coding summary 

- collaboration/retrospectives/3_data_analysis_group_retrospective.md
- collaboration/retrospectives/3_data_analysis_individual_reflections.md
---
This Pull Request finalizes and adds the retrospective documents for **Milestone 3: Data Analysis**.
**Key changes in this PR include:**
* **Renaming** the main retrospective document for clarity:
`collaboration/retrospectives/3_data_analysis.md` -> `collaboration/retrospectives/3_data_analysis_group_retrospective.md`
* **Updating the content** of the Group Retrospective with final insights, lessons learned, and action plans.
* **Adding the new Individual Retrospective file:**
`collaboration/retrospectives/3_data_analysis_individual_reflections.md`
* Integrating a link from the Group Retrospective to the Individual Reflections for easy navigation.
---
---
Closes #182
> Doc: Add M3 Data Analysis Retrospectives

- README.md
---
This PR adds new updates to the main ReadME
- Research Conclusions
- Non Technical Findings
- Analysis Summary
- Confidence in Conclusions
- Limitations
- Ideas for Future Research 
---
> Update Main readme

- collaboration/retrospectives/3_data_analysis_individual_reflections.md
---
This Pull Request finalizes and adds the retrospective documents for **Milestone 3: Data Analysis**.
**Key changes in this PR include:**
* **Renaming** the main retrospective document for clarity:
`collaboration/retrospectives/3_data_analysis.md` -> `collaboration/retrospectives/3_data_analysis_group_retrospective.md`
* **Updating the content** of the Group Retrospective with final insights, lessons learned, and action plans.
* **Adding the new Individual Retrospective file:**
`collaboration/retrospectives/3_data_analysis_individual_reflections.md`
* Integrating a link from the Group Retrospective to the Individual Reflections for easy navigation.
---
---
Closes #182
> Minor fixes in individual retro file

- 1_datasets/README.md
- 3_data_exploration/README.md
---
Small change on the Dataset Readme 
---
Including the processed datasets in the datasets readme and linking them
> Dataset readme

- README.md
---
Change the logo in the main README file to the latest one.
closes #209
> Update Team logo

- 4_data_analysis/README.md
- 4_data_analysis/mixed_methods_findings.md
- README.md
This PR includes refinements to the main `README.md` and `4_data_analysis/README.md` for clarity and consistency. It also renames and updates links to the findings document (`mixed_methods_findings.md`).
Closes: #212 
---
---
---
* Please help address the broken main README logo image. It needs to be uploaded directly to the repo.
* Please review the new phrasing in the 'Research Conclusion' section for impact.
* Check the clarity of the updated 'Methods at a Glance' section.
> Refactor: Updated READMEs for clarity and integrated findings.

- collaboration/meeting_minutes/milestone_4_08_04_meeting_22.md
---
Meeting 22: Reviewing Personas & Suggesting Artifacts
---
In our August 4th planning meeting, the team reviewed and refined our target personas, and agreed to continue the discussion on WhatsApp to finalize them. We also aligned on potential communication artifacts (LinkedIn and a website) and reviewed Omnia’s workflow to identify our current progress. Next steps include finalizing personas, assigning tasks, and planning the artifact development process.
closes #219
> Add meeting 22 minutes

- collaboration/meeting_minutes/milestone_4_08_04_meeting_23.md
- collaboration/meeting_minutes/milestone_4_08_06_meeting_24.md
---
Meeting Minute 24
---
Preparing the meeting minutes 24 with what we have discussed about the Artifacts and our Page.
> Preparing Meeting minutes #24

- README.md
---
Readme adjustments
---
To prepare the main readme for the communications milestone.
> Preparing the Main readme file for Communications Milestone
